# Generated by Django 3.2.4 on 2022-02-20 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BusinessOwener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=30)),
                ('PSellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PActualPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PMargin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PUnit', models.PositiveIntegerField()),
                ('PAvailiblity', models.BooleanField(default=True)),
                ('PDelivery', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('PImage', models.ImageField(upload_to='upload/images/')),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessOwener.storeprofile')),
                ('PCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_category')),
                ('PSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_subcategory')),
            ],
        ),
    ]
