# Generated by Django 3.2.4 on 2022-02-19 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='stroetiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('Time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='storeprofile',
            fields=[
                ('BID', models.BigAutoField(primary_key=True, serialize=False)),
                ('BStoreName', models.CharField(max_length=50)),
                ('BPinCode', models.PositiveIntegerField()),
                ('BAddressLine1', models.TextField(max_length=100)),
                ('BAddressLine2', models.TextField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
